# Generated by Django 3.0.3 on 2020-07-14 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teach_app_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='student_enrol_key',
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='teacher_enrol_key',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
