# Generated by Django 3.0.3 on 2020-07-28 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teach_app_backend', '0002_auto_20200728_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='feedback',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='grade',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=4, null=True),
        ),
    ]
