# Generated by Django 3.0.3 on 2020-07-03 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teach_app_backend', '0002_auto_20200703_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='lecture_name',
        ),
    ]
